# Generated by Django 5.0 on 2023-12-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='song_cover',
            field=models.ImageField(default='covers/default/d_cover.jpg', upload_to='covers/'),
        ),
    ]
